"""IMDb per-episode filming-location listings for seasons 2–5 and I Want to Believe (read 2026-10-06),
kept only where they add a street address or a site the book doesn't give. Row: ep, title, name, addr, city, played, note, query."""
ROWS = [
("2X03","Blood","UBC Main Mall","1956 Main Mall, UBC","Vancouver","Scene not specified by the listing",None,"1956 Main Mall, Vancouver, BC"),
("2X04","Sleepless","West 13th Avenue","758 W. 13th Ave","Vancouver","Scene not specified by the listing",None,"758 West 13th Avenue, Vancouver, BC"),
("2X05","Duane Barry","Dunbar Street","4540 Dunbar St","Vancouver","Scene not specified by the listing",None,"4540 Dunbar Street, Vancouver, BC"),
("2X08","One Breath","Hotel Vancouver","900 W. Georgia St","Vancouver","Scene not specified by the listing",None,"900 West Georgia Street, Vancouver, BC"),
("2X12","Aubrey","First Street, New Westminster","234 1st St","New Westminster","Scene not specified by the listing",None,"234 1st Street, New Westminster, BC"),
("2X13","Irresistible","St. Peter's Roman Catholic Cemetery","Cemetery not further identified","New Westminster","Cemetery",None,"Fraser Cemetery, New Westminster, BC"),
("2X13","Irresistible","Mountain View Cemetery","Fraser St & E. 39th Ave","Vancouver","Cemetery",None,"Mountain View Cemetery, Vancouver, BC"),
("2X16","Colony","Mulder's mother's house","3268 W. 49th Ave","Vancouver","Mrs. Mulder's house (also Anasazi and The Blessing Way)",None,"3268 West 49th Avenue, Vancouver, BC"),
("2X16","Colony","72nd St at Churchill St","72 St & Churchill St","Delta","Scene not specified by the listing",None,"72 Street and Churchill Street, Delta, BC"),
("2X16","Colony","Lions Gate Travelodge","2060 Marine Dr","North Vancouver","Motel",None,"2060 Marine Drive, North Vancouver, BC"),
("2X17","End Game","Cassiar Street","800 Cassiar St","Vancouver","Scene not specified by the listing",None,"800 Cassiar Street, Vancouver, BC"),
("2X18","Fearful Symmetry","Carrall Street","464 Carrall St","Vancouver","Scene not specified by the listing",None,"464 Carrall Street, Vancouver, BC"),
("2X21","The Calusari","Riverview Hospital","2601 Lougheed Hwy","Coquitlam","Scene not specified by the listing",None,"Riverview Hospital, Coquitlam, BC"),
("2X21","The Calusari","Fifth Street, New Westminster","411 5th St","New Westminster","Scene not specified by the listing (likely the Holvey house)",None,"411 5th Street, New Westminster, BC"),
("2X23","Soft Light","Mountain View Cemetery","Fraser St & E. 39th Ave","Vancouver","Scene not specified by the listing",None,"Mountain View Cemetery, Vancouver, BC"),
("2X25","Anasazi","Mulder's mother's house","3268 W. 49th Ave","Vancouver","Mrs. Mulder's house",None,"3268 West 49th Avenue, Vancouver, BC"),
("3X01","The Blessing Way","Mulder's mother's house","3268 W. 49th Ave","Vancouver","Mrs. Mulder's house",None,"3268 West 49th Avenue, Vancouver, BC"),
("3X01","The Blessing Way","Scully's apartment","1419 Pendrell St","Vancouver","Scully's apartment exterior","Listed as 1442 Pendrell St.","1419 Pendrell Street, Vancouver, BC"),
("3X02","Paper Clip","Lynnwood Inn","1515 Barrow St","North Vancouver","Scene not specified by the listing",None,"Lynnwood Inn, North Vancouver, BC"),
("3X03","D.P.O.","Marine Drive at Fell Avenue","Marine Dr & Fell Ave","North Vancouver","Scene not specified by the listing",None,"Marine Drive and Fell Avenue, North Vancouver, BC"),
("3X05","The List","Riverview Hospital","2601 Lougheed Hwy","Coquitlam","Eastpoint State Penitentiary",None,"Riverview Hospital, Coquitlam, BC"),
("3X06","2Shy","The Shipyards, Lower Lonsdale","Foot of Lonsdale Ave","North Vancouver","Scene not specified by the listing",None,"The Shipyards, North Vancouver, BC"),
("3X08","Oubliette","Fromme Road","3448 Fromme Rd","North Vancouver","Scene not specified by the listing",None,"3448 Fromme Road, North Vancouver, BC"),
("3X09","Nisei","Bellevue Avenue","2598 Bellevue Ave","West Vancouver","Near the overpass Mulder jumps from",None,"2598 Bellevue Avenue, West Vancouver, BC"),
("3X11","Revelations","196A Street, Langley","6017 196A St","Langley","Scene not specified by the listing",None,"6017 196A Street, Langley, BC"),
("3X17","Pusher","Burrard Street","1081 Burrard St","Vancouver","Scene not specified by the listing (St. Paul's Hospital block)",None,"1081 Burrard Street, Vancouver, BC"),
("3X18","Teso Dos Bichos","Rice Lake parking lot (former GVRD works site)","Lillooet Rd","North Vancouver","Excavation site in Ecuador",None,"Rice Lake, North Vancouver, BC"),
("3X20","Jose Chung's From Outer Space","East Hastings Street","272 E. Hastings St","Vancouver","Scene not specified by the listing",None,"272 East Hastings Street, Vancouver, BC"),
("3X21","Avatar","Davie Street","556 Davie St","Vancouver","Scene not specified by the listing",None,"556 Davie Street, Vancouver, BC"),
("3X21","Avatar","Bute Street at Melville Street","Bute St & Melville St","Vancouver","Scene not specified by the listing",None,"Bute Street and Melville Street, Vancouver, BC"),
("3X24","Talitha Cumi","Mulder family summer house","2429 Christopherson Rd","Surrey","Mrs. Mulder's summer house",None,"2429 Christopherson Road, Surrey, BC"),
("4X01","Herrenvolk","Old army barracks","Kamloops","Kamloops","Old army barracks",None,"Kamloops, BC"),
("4X08","Paper Hearts","Lions Gate Travelodge","2060 Marine Dr","North Vancouver","Motel",None,"2060 Marine Drive, North Vancouver, BC"),
("4X11","El Mundo Gira","East Kent Avenue North at Borden Street","E. Kent Ave N & Borden St","Vancouver","Where Mulder and Lozano question the day workers",None,"East Kent Avenue North and Borden Street, Vancouver, BC"),
("4X14","Leonard Betts","Elaine Tanner's house","441 Glen Dr","Vancouver","Elaine Tanner's house",None,"441 Glen Drive, Vancouver, BC"),
('4X19', 'Synchrony', 'West Georgia Street', '817 W. Georgia St', 'Vancouver', 'Scene not specified by the listing', None, '817 West Georgia Street, Vancouver, BC'),
('4X23', 'Demons', 'Stayte Road', '924 Stayte Rd', 'Surrey', 'Scene not specified by the listing', None, '924 Stayte Road, Surrey, BC'),
('5X01', 'Unusual Suspects', 'Cambie Street', '328 Cambie St', 'Vancouver', 'Scene not specified by the listing (the abduction corner near the Dominion Building)', None, '328 Cambie Street, Vancouver, BC'),
('5X03', 'Redux II', 'Water Street', '350 Water St', 'Vancouver', 'Scene not specified by the listing (the Georgetown street)', None, '350 Water Street, Vancouver, BC'),
('5X04', 'Detour', 'Lions Gate Travelodge', '2060 Marine Dr', 'North Vancouver', 'Motel', 'Listed as 2036 Marine Dr.', '2060 Marine Drive, North Vancouver, BC'),
('5X16', "Mind's Eye", 'Blarney Stone pub', '216 Carrall St', 'Vancouver (Gastown)', 'The bar where Mulder and Scully wait for the killer', None, '216 Carrall Street, Vancouver, BC'),
]
