"""Season 2 (1994–95) locations from the location managers' book, pages 55–81.
Row: ep, title, name, address, city, played, note, geocode query."""
ROWS = [
("2X01","Little Green Men","Seymour Demonstration Forest","Lower Seymour Conservation Reserve","North Vancouver","Arecibo rainforest, Puerto Rico","Used again as Costa Rica for F. Emasculata.","Lower Seymour Conservation Reserve, North Vancouver, BC"),
("2X01","Little Green Men","Plaza of Nations","770 Pacific Blvd S","Vancouver","Florida airport",None,"770 Pacific Boulevard, Vancouver, BC"),
("2X02","The Host","Iona Island sewage treatment plant","Iona Island Causeway","Richmond","Newark sewage treatment plant",None,"Iona Island Wastewater Treatment Plant, Richmond, BC"),
("2X02","The Host","Port Mann hydro substation","14115 King Rd","Surrey","Russian freighter engine room","A 1950s backup substation, never used; it returned as the ship's boiler room in Patient X.","14115 King Road, Surrey, BC"),
("2X03","Blood","Army & Navy department store","502 Columbia St","New Westminster","Department store where the displays turn murderous",None,"502 Columbia Street, New Westminster, BC"),
("2X03","Blood","First Capital Building","New Westminster Quay","New Westminster","Office tower lobby",None,"First Capital Place, New Westminster, BC"),
("2X03","Blood","UBC clock tower","Ladner Clock Tower, UBC","Vancouver","Campus clock tower (exterior only; the interior was a set)",None,"Ladner Clock Tower, University of British Columbia, Vancouver, BC"),
("2X03","Blood","Main Service Automobile Centre","298 Alexander St","Vancouver","Auto repair shop",None,"298 Alexander Street, Vancouver, BC"),
("2X03","Blood","Evelyn Saller Centre","320 Alexander St","Vancouver","Hospital",None,"320 Alexander Street, Vancouver, BC"),
("2X03","Blood","Old YMCA","6th St at Queens Ave","New Westminster","Police precinct lockers","Also the police station, coroner's office, prison and medical centre in Aubrey.","6th Street and Queens Avenue, New Westminster, BC"),
("2X04","Sleepless","Two-Jays Café","81 W. Pender St","Vancouver","Kay's Diner, the truck stop","Sister Samantha visits Mulder here again in Redux II.","81 West Pender Street, Vancouver, BC"),
("2X04","Sleepless","Pacific Central Station","1150 Station St","Vancouver","Bronx train station and platform",None,"1150 Station Street, Vancouver, BC"),
("2X04","Sleepless","General Motors Place (now Rogers Arena), under construction","800 Griffiths Way","Vancouver","Construction site where Mr. X is introduced (establishing shot only; close-ups reshot on stage)",None,"Rogers Arena, Vancouver, BC"),
("2X04","Sleepless","Willow Pavilion, Vancouver General Hospital","855 W. 12th Ave","Vancouver","V.A. Medical Center: the third-floor ward and the basement service tunnels (Cole's cell)",None,"Willow Pavilion, Vancouver General Hospital, Vancouver, BC"),
("2X05","Duane Barry","UBC Aquatic Centre and Chemistry Building","6121 University Blvd","Vancouver","Pool where Mulder swims; FBI office (spectrometer lab); hospital room",None,"UBC Aquatic Centre, Vancouver, BC"),
("2X05","Duane Barry","Waterfront Centre Hotel and Tower","900 Canada Place Way / 200 Burrard St","Vancouver","Travel agency hostage scene, command centre, and Scully's office (the community police office)",None,"Waterfront Centre, 200 Burrard Street, Vancouver, BC"),
("2X05","Duane Barry","St. George's School","3851 W. 29th Ave","Vancouver","Treatment centre",None,"3851 West 29th Avenue, Vancouver, BC"),
("2X06","Ascension","Scully's apartment","1419 Pendrell St","Vancouver","Exterior of Scully's apartment, from here on",None,"1419 Pendrell Street, Vancouver, BC"),
("2X06","Ascension","Grouse Mountain Skyride","6400 Nancy Greene Way","North Vancouver","Skyland Mountain tram","The parking lot, chalet and backroad were shot at Mount Seymour.","Grouse Mountain Skyride, North Vancouver, BC"),
("2X06","Ascension","Mount Seymour","Mount Seymour Rd","North Vancouver","Skyland Mountain parking lot, chalet and the backroad Duane Barry drives",None,"Mount Seymour Resort, North Vancouver, BC"),
("2X06","Ascension","Robson Square","800 Robson St","Vancouver","Park with the waterfall where Mulder meets Mrs. Scully",None,"Robson Square, Vancouver, BC"),
("2X06","Ascension","Vancouver Art Gallery","750 Hornby St","Vancouver","Senator Matheson's office, interior and exterior",None,"750 Hornby Street, Vancouver, BC"),
("2X07","3","Kristen's house","2700-block SW Marine Dr","Vancouver","Kristen Kilar's house and pool","A private residence; the owner at the time was Pavel Bure.","2700 Southwest Marine Drive, Vancouver, BC"),
("2X09","Firewalker","Seymour Demonstration Forest","Lower Seymour Conservation Reserve","North Vancouver","Mount Avalon field base exterior",None,"Lower Seymour Conservation Reserve, North Vancouver, BC"),
("2X09","Firewalker","Vacant B.C. Hydro substation","Site not named","Lower Mainland","Field base interior","The book gives no address.",None),
("2X10","Red Museum","Uncle Herbert's Fish and Chips","4866 Delta St","Delta (Ladner)","Clay's BBQ restaurant and the Wisconsin town street",None,"4866 Delta Street, Delta, BC"),
("2X10","Red Museum","J & L Beef","Cloverdale","Surrey","Meat packing plant","Street address not given.","J & L Beef, Cloverdale, Surrey, BC"),
("2X10","Red Museum","Burns Bog pasture","Burns Bog","Delta","Plane crash site in the field",None,"Burns Bog, Delta, BC"),
("2X11","Excelsis Dei","Riverview Hospital (West Lawn and Crease Clinic)","2601 Lougheed Hwy","Coquitlam","Excelsis Dei convalescent home",None,"Riverview Hospital, Coquitlam, BC"),
("2X12","Aubrey","Timberland Motel","3418 King George Hwy","Surrey","Motel",None,"3418 King George Boulevard, Surrey, BC"),
("2X12","Aubrey","The Cokely house","13275 Colebrook Rd","Surrey","Harry Cokely's house and the field where the bodies are exhumed","Returned as the Peacock house in Home.","13275 Colebrook Road, Surrey, BC"),
("2X12","Aubrey","Old YMCA","6th St at Queens Ave","New Westminster","Police station, coroner's office, prison and medical centre",None,"6th Street and Queens Avenue, New Westminster, BC"),
("2X15","Fresh Bones","Versatile Shipyard","109 E. Esplanade","North Vancouver","Folkstone refugee processing centre",None,"109 East Esplanade, North Vancouver, BC"),
("2X15","Fresh Bones","North Shore Cemetery","Lillooet Rd","North Vancouver","Cemetery where the grave is dug",None,"North Vancouver Cemetery, Lillooet Road, North Vancouver, BC"),
("2X16","Colony","Mulder's father's house","6476 Blenheim St","Vancouver","Bill Mulder's house on Martha's Vineyard","Used three times over the years.","6476 Blenheim Street, Vancouver, BC"),
("2X16","Colony","Broughton Street apartments","1091 Broughton St","Vancouver","Dr. Dickens's apartment, where the stuntman goes out the window",None,"1091 Broughton Street, Vancouver, BC"),
("2X17","End Game","Lions Gate Travelodge","2060 Marine Dr","North Vancouver","Motor lodge","Used on at least ten occasions over the run.","2060 Marine Drive, North Vancouver, BC"),
("2X18","Fearful Symmetry","Country road, South Surrey","Road not named","Surrey","Road where the elephant runs","The only municipality that would allow a circus animal on a public road.","South Surrey, BC"),
("2X18","Fearful Symmetry","555 Jervis Street parkade (then under construction)","555 Jervis St","Vancouver","Construction site where the tiger is cornered",None,"555 Jervis Street, Vancouver, BC"),
("2X19","Død Kalm","HMCS Mackenzie at Barry Point","Penzance Dr","Burnaby","USS Ardent","The destroyer was later sunk as an artificial reef.","Barnet Marine Park, Burnaby, BC"),
("2X19","Død Kalm","Jericho Sailing Club","1300 Discovery St","Vancouver","ICU and the Norwegian bar",None,"1300 Discovery Street, Vancouver, BC"),
("2X20","Humbug","Memorial Camp (Royal Canadian Legion)","16327 Beach Rd","White Rock","Gulf Breeze trailer park",None,"16327 Beach Road, Surrey, BC"),
("2X20","Humbug","Semiahmoo Park","15782 Marine Dr area","White Rock","Florida cemetery for Glazebrook's funeral",None,"Semiahmoo Park, White Rock, BC"),
("2X20","Humbug","Glazebrook's house","1120 Harold St","North Vancouver","Gerald Glazebrook's backyard pool",None,"1120 Harold Street, North Vancouver, BC"),
("2X22","F. Emasculata","Deltaport Farm Market","2757 52nd St","Delta","Rural gas station where the helicopter lands",None,"2757 52 Street, Delta, BC"),
("2X22","F. Emasculata","Dennison Dodge/Chrysler","Hwy 17 at Vassey Rd","Delta","Greyhound bus station",None,"Highway 17 and Vassey Road, Delta, BC"),
("2X22","F. Emasculata","Seymour Demonstration Forest","Lower Seymour Conservation Reserve","North Vancouver","Costa Rican rainforest",None,"Lower Seymour Conservation Reserve, North Vancouver, BC"),
("2X23","Soft Light","Pacific Central Station","1150 Station St","Vancouver","Train station and platform",None,"1150 Station Street, Vancouver, BC"),
("2X23","Soft Light","Rear of 48 W. Hastings St","48 W. Hastings St","Vancouver","Alley",None,"48 West Hastings Street, Vancouver, BC"),
("2X23","Soft Light","Pacific Marine Training Institute","265 W. Esplanade","North Vancouver","AM building",None,"265 West Esplanade, North Vancouver, BC"),
("2X24","Our Town","The Hollies (Chaco mansion)","1388 The Crescent","Vancouver (Shaughnessy)","Walter Chaco's mansion",None,"1388 The Crescent, Vancouver, BC"),
("2X24","Our Town","Woodward Slough","No. 4 Rd at Finn Rd","Richmond","Ditch where the truck goes in and the bones are dredged",None,"No. 4 Road and Finn Road, Richmond, BC"),
("2X25","Anasazi","Red Rock Quarry","4892 Quarry Rd","Coquitlam","New Mexico desert and the buried boxcar; painted red","Used again for The Blessing Way.","4892 Quarry Road, Coquitlam, BC"),
]
