"""Season 3 (1995–96) locations from the location managers' book, pages 84–. (Partial; continued below as read.)
Row: ep, title, name, address, city, played, note, geocode query."""
ROWS = [
("3X01","The Blessing Way","Red Rock Quarry","4892 Quarry Rd","Coquitlam","Sedona, Arizona: the painted desert",None,"4892 Quarry Road, Coquitlam, BC"),
("3X02","Paper Clip","Britannia Mine (B.C. Museum of Mining)","Britannia Beach","Squamish-Lillooet","Abandoned West Virginia mine with the filing cabinets; the UFO lift-off was lit from a crane outside","Closed to the public for seven days.","Britannia Mine Museum, Britannia Beach, BC"),
("3X02","Paper Clip","Tea Shoppe","Britannia Beach","Squamish-Lillooet","Diner",None,"Britannia Beach, BC"),
("3X02","Paper Clip","Southlands Nursery","6550 Balaclava St","Vancouver","Orchid hothouse",None,"6550 Balaclava Street, Vancouver, BC"),
("3X03","D.P.O.","Jackson homestead","24554 102 Ave","Maple Ridge (Albion)","Darin Oswald's house and the pasture where the cows are struck",None,"24554 102 Avenue, Maple Ridge, BC"),
("3X04","Clyde Bruckman's Final Repose","3500-block Commercial Street","3500-block Commercial St","Vancouver","Street, tarot dealership and palm reader",None,"3550 Commercial Street, Vancouver, BC"),
("3X04","Clyde Bruckman's Final Repose","Ernie's Grocery","3599 Commercial St","Vancouver","Convenience and liquor store",None,"3599 Commercial Street, Vancouver, BC"),
("3X06","2Shy","Quebec Street","2500–2600-block Quebec St","Vancouver","Virgil Incanto's apartment and Ellen's condo, a block apart",None,"2550 Quebec Street, Vancouver, BC"),
("3X07","The Walk","Blake Hall, former Justice Institute of B.C.","4180 W. 4th Ave","Vancouver","Interrogation room, hallways, detention centre and Roach's cell; the pool next door was the swimming pool","Demolished within months; later the McDonald Building here was Pusher's FBI firing range and hearing room.","4180 West 4th Avenue, Vancouver, BC"),
("3X07","The Walk","Callahan house","3638 Osler St","Vancouver","General Callahan's house",None,"3638 Osler Street, Vancouver, BC"),
("3X07","The Walk","Jean Matheson Pavilion, B.C. Children's Hospital","4480 Oak St","Vancouver","Psych ward isolation room, hallway, elevator and stairwell",None,"4480 Oak Street, Vancouver, BC"),
("3X07","The Walk","Old Nurses Residence, Vancouver General Hospital","855 W. 12th Ave","Vancouver","Callahan's office, observation room and hallway",None,"Vancouver General Hospital, Vancouver, BC"),
("3X08","Oubliette","Mount Seymour Lodge","Mount Seymour Rd","North Vancouver","Carl Wade's house in the middle of nowhere","350 trees were brought in to hide the ski lift.","Mount Seymour Resort, North Vancouver, BC"),
("3X08","Oubliette","Seymour River, Squamish Nation land","320 Seymour Blvd","North Vancouver","Riverbank where Amy is found","Moved from Twin Bridges after the river rose; 1,000 trees hid the houses opposite.","320 Seymour Boulevard, North Vancouver, BC"),
("3X09","Nisei","Betsy Hagopian's house","Grand Blvd","North Vancouver","Betsy Hagopian's house (also the MUFON house in Memento Mori)","Street number not given.","Grand Boulevard, North Vancouver, BC"),
("3X09","Nisei","Ballantyne Pier","655 Centennial Rd","Vancouver","Coast Guard HQ and the harbourmaster's office","Also both airports and the Piper Maru dock in Piper Maru.","Ballantyne Pier, Vancouver, BC"),
("3X09","Nisei","B.C. Rail station","1311 W. 1st St","North Vancouver","Edwards Terminal, Queensgate, Ohio: the train station, platform and railyard",None,"1311 West 1st Street, North Vancouver, BC"),
("3X09","Nisei","Alice Street overpass","26th St at Bellevue Ave","West Vancouver","Pedestrian overpass Mulder jumps from onto the train",None,"26th Street and Bellevue Avenue, West Vancouver, BC"),
("3X09","Nisei","Hycroft Manor","1489 McRae Ave","Vancouver","Japanese Embassy, Washington",None,"1489 McRae Avenue, Vancouver, BC"),
("3X09","Nisei","Pier 94, Vancouver Shipyards","Pier 94","North Vancouver","Drydock and the Talapus",None,"Vancouver Shipyards, North Vancouver, BC"),
("3X10","731","Porteau Cove","Squamish Hwy","Porteau Cove","Where the train car is blown up",None,"Porteau Cove Provincial Park, BC"),
("3X12","War of the Coprophages","Crane Canada","225 North Rd","Coquitlam","Methane plant interior","The exterior was a neighbouring warehouse.","225 North Road, Coquitlam, BC"),
("3X12","War of the Coprophages","Petro-Canada, Dollarton","489 N. Dollarton Hwy","North Vancouver","Mini-mart where the locals panic-buy",None,"489 North Dollarton Highway, North Vancouver, BC"),
("3X12","War of the Coprophages","Clairmont Camera, North Shore Studios","555 Brooksbank Ave","North Vancouver","Small-town hospital exterior",None,"555 Brooksbank Avenue, North Vancouver, BC"),
("3X13","Syzygy","Old Cypress Mountain quarry","Cypress Bowl Rd","West Vancouver","Clearing and cliff where the boy's body hangs",None,"Cypress Bowl Road, West Vancouver, BC"),
("3X13","Syzygy","Boundary Bay Airport","7800 Alpha Way","Delta","Townsfolk night shoot (the extras' tent burned)",None,"Boundary Bay Airport, Delta, BC"),
("3X14","Grotesque","Heritage Hall","3102 Main St","Vancouver","Art studio, historical building with the gargoyle",None,"3102 Main Street, Vancouver, BC"),
("3X14","Grotesque","Alley at Bonanza Meat Market","1st St at Lonsdale Ave","North Vancouver","Dark alley, painted to match Heritage Hall",None,"1st Street and Lonsdale Avenue, North Vancouver, BC"),
("3X15","Piper Maru","Ho-Ho Chop Suey House","102 E. Pender St","Vancouver","Hong Kong restaurant","Reused for Hell Money.","102 East Pender Street, Vancouver, BC"),
("3X15","Piper Maru","Jericho Garrison (DND), Ortona Crescent","Ortona Cres","Vancouver","Miramar Naval Air Base and Commander Johansen's house","Also the young CSM's Fort Bragg barracks in Musings; a set based on it was Bill Scully's house.","Jericho Garrison, Vancouver, BC"),
("3X15","Piper Maru","Ajatan Studios","Railway St","North Vancouver","Kallenchuck's salvage office, under the Second Narrows Bridge",None,"Railway Street, North Vancouver, BC"),
("3X15","Piper Maru","Gauthier's apartment","3215 Victoria Dr","Vancouver","Gauthier's San Francisco apartment",None,"3215 Victoria Drive, Vancouver, BC"),
("3X15","Piper Maru","Charlotte Explorer at Ballantyne Pier / Berry Point","Ballantyne Pier","Vancouver","The Piper Maru",None,"Ballantyne Pier, Vancouver, BC"),
("3X16","Apocrypha","Robson Square skating rink","800 Robson St","Vancouver","Ice rink; the Lone Gunmen cross Howe St to Mulder's car",None,"Robson Square, Vancouver, BC"),
("3X16","Apocrypha","Stanley Park, near the Rose Garden","Stanley Park","Vancouver","Cemetery",None,"Stanley Park Rose Garden, Vancouver, BC"),
("3X17","Pusher","Takaya Golf Centre","700 Apex Ave","North Vancouver","Driving range where Modell is arrested",None,"700 Apex Avenue, North Vancouver, BC"),
("3X17","Pusher","False Creek Grocery","760 W. 6th Ave","Vancouver","Mt. Foodmore supermarket; the parking lot across the street was the Beltway commuter lot",None,"760 West 6th Avenue, Vancouver, BC"),
("3X17","Pusher","McDonald Building, former Justice Institute","4180 W. 4th Ave","Vancouver","FBI firing range and hearing room",None,"4180 West 4th Avenue, Vancouver, BC"),("3X18","Teso Dos Bichos","Riverview Hospital site","2601 Lougheed Hwy","Coquitlam","Boston museum, morgue, grad office and parking lot (eleven sets built here)",None,"Riverview Hospital, Coquitlam, BC"),
("3X19","Hell Money","W.I.S.E. Hall","1882 Adanac St","Vancouver","The Chinese gaming hall with the balconies",None,"1882 Adanac Street, Vancouver, BC"),
("3X19","Hell Money","Ho-Ho Chop Suey House and 100-block East Pender","102 E. Pender St","Vancouver","Chinatown street and restaurant",None,"102 East Pender Street, Vancouver, BC"),
("3X19","Hell Money","Crease Clinic, Riverview Hospital","2601 Lougheed Hwy","Coquitlam","Standing sets for the episode",None,"Riverview Hospital, Coquitlam, BC"),
("3X20","Jose Chung's From Outer Space","Ovaltine Café","251 E. Hastings St","Vancouver","The diner",None,"251 East Hastings Street, Vancouver, BC"),
("3X20","Jose Chung's From Outer Space","Woodlands Hospital site, Centre Building","9 E. Columbia St","New Westminster","Hospital, autopsy room, motel room, community centre, medical office, military room and Harold's car","More than 21 episodes used the Woodlands site; it became known as Studio Four.","9 East Columbia Street, New Westminster, BC"),
("3X21","Avatar","The Gerard Lounge, Sutton Place Hotel","845 Burrard St","Vancouver","Chesapeake Lounge",None,"845 Burrard Street, Vancouver, BC"),
("3X21","Avatar","Hotel Vancouver, 14th floor","900 W. Georgia St","Vancouver","Ambassador Hotel room where Skinner wakes up",None,"900 West Georgia Street, Vancouver, BC"),
("3X21","Avatar","Viva Tower, suite 1706","1311 Howe St","Vancouver","The madam's condominium","Skinner's own apartment was at 1180 Richards St (set).","1311 Howe Street, Vancouver, BC"),
("3X22","Quagmire","Pitt Lake","Pitt Lake, end of Rannie Rd","Pitt Meadows","Fishing dock, Ted's Bait and Tackle, lakefront; the driving scene was on Neaves Rd",None,"Pitt Lake, Pitt Meadows, BC"),
("3X22","Quagmire","Buntzen Lake","Sunnyside Rd","Anmore","Rocky lakefront, the quagmire reeds and the RV park",None,"Buntzen Lake, Anmore, BC"),
("3X22","Quagmire","Rice Lake, Seymour Demonstration Forest","Lower Seymour Conservation Reserve","North Vancouver","The lake where Big Blue surfaces",None,"Rice Lake, North Vancouver, BC"),
("3X22","Quagmire","B.C. Research wave tank","3650 Wesbrook Mall, UBC","Vancouver","The rock where Mulder and Scully are stranded (built in the wave tank)",None,"3650 Wesbrook Mall, Vancouver, BC"),
("3X23","Wetwired","2400 Court Motel","2400 Kingsway","Vancouver","Mirador Motel: Scully's room 274, Mulder's room 127","Revisited for The Pine Bluff Variant.","2400 Kingsway, Vancouver, BC"),
("3X23","Wetwired","Hazelgrove Farm","Fort Langley","Langley","Hazelnut orchard where the bodies are buried","Returned for Schizogeny.","Hazelgrove Farm, Fort Langley, BC"),
("3X23","Wetwired","Riddock's house","3792 W. 1st Ave","Vancouver","Joseph Patnik's neighbour's house and the lane with the cable pole",None,"3792 West 1st Avenue, Vancouver, BC"),
("3X23","Wetwired","Safe house","6120 MacDonald St","Vancouver","The safe house where Mulder finds the cable van",None,"6120 MacDonald Street, Vancouver, BC"),
("3X24","Talitha Cumi","A&W","6535 Kingsway","Burnaby","Fast-food restaurant where Jeremiah Smith heals the shooting victims",None,"6535 Kingsway, Burnaby, BC"),
("3X24","Talitha Cumi","Vancouver City Hall","453 W. 12th Ave","Vancouver","Social services lobby",None,"453 West 12th Avenue, Vancouver, BC"),
("3X24","Talitha Cumi","Granville Square","200 Granville St","Vancouver","FBI headquarters lobby","Also the FBI lobby in Pusher; not SFU as sometimes printed.","200 Granville Street, Vancouver, BC"),
("3X24","Talitha Cumi","Tolko sawmill","Dollarton area","North Vancouver","The sawmill where the Bounty Hunter chases Smith","Burned down late 1997; its lot was the RV park in Bad Blood.","Dollarton Highway, North Vancouver, BC"),
("3X24","Talitha Cumi","Mulder family beach house","Surrey","Surrey","Mulder's mother's beach house","Street not given.","Crescent Beach, Surrey, BC"),
("3X17","Pusher","Granville Square","200 Granville St","Vancouver","FBI headquarters lobby",None,"200 Granville Street, Vancouver, BC"),
]
