"""Season 4 (1996–97) locations from the location managers' book, pages 118–. (Partial; continued as read.)"""
ROWS = [
("4X01","Herrenvolk","Chai-Na-Ta ginseng farm","Walhachin","Thompson-Nicola","The golden fields where the bees swarm",None,"Walhachin, BC"),
("4X01","Herrenvolk","Walhachin","Walhachin","Thompson-Nicola","The shanty town where the clones live","The only time the show went more than 100 miles from Vancouver.","Walhachin, BC"),
("4X01","Herrenvolk","Flavelle Cedar mill","Port Moody","Port Moody","Sawmill interiors for the night chase",None,"Flavelle Cedar, Port Moody, BC"),
("4X01","Herrenvolk","Tolko sawmill","Dollarton area","North Vancouver","Sawmill exteriors",None,"Dollarton Highway, North Vancouver, BC"),
("4X02","Unruhe","Maple Leaf Pharmacy","2406 Nanaimo St","Vancouver","Drugstore and the alley, with the rain towers",None,"2406 Nanaimo Street, Vancouver, BC"),
("4X02","Unruhe","North Vancouver Cemetery","Lillooet Rd","North Vancouver","Cemetery, with the RV hidden in the gravel yard","Led to a moratorium on filming in North Shore cemeteries.","North Vancouver Cemetery, Lillooet Road, North Vancouver, BC"),
("4X03","Home","Fort Langley Community Hall","9167 Glover Rd","Langley (Fort Langley)","Police station exterior and the town square","Interiors were built at the Langley Fine Arts School.","9167 Glover Road, Langley, BC"),
("4X03","Home","The Cokely house","13275 Colebrook Rd","Surrey","The Peacock house and the baseball field",None,"13275 Colebrook Road, Surrey, BC"),
("4X04","Teliko","Demolition site","303–305 Railway St","Vancouver","Building being demolished",None,"303 Railway Street, Vancouver, BC"),
("4X04","Teliko","Demott Avenue","500 Alexander St and rear alley","Vancouver","Demott Avenue, Philadelphia",None,"500 Alexander Street, Vancouver, BC"),
("4X06","Sanguinarium","Mount Saint Joseph's Hospital","3080 Prince Edward St","Vancouver","Greenwood Memorial Hospital: ER, day surgery, second floor",None,"3080 Prince Edward Street, Vancouver, BC"),
("4X07","Musings of a Cigarette Smoking Man","Texas Book Depository stand-in","1190 Homer St","Vancouver","Texas School Book Depository, interior and exterior",None,"1190 Homer Street, Vancouver, BC"),
("4X07","Musings of a Cigarette Smoking Man","Andy Livingstone Park","Carrall St at Expo Blvd","Vancouver","Dealey Plaza and the grassy knoll; motorcade shot from the pedestrian overpass and a GM Place parking lot",None,"Andy Livingstone Park, Vancouver, BC"),
("4X07","Musings of a Cigarette Smoking Man","Jericho Garrison","Ortona Cres","Vancouver","Young CSM's Fort Bragg barracks",None,"Jericho Garrison, Vancouver, BC"),
("4X08","Paper Hearts","United Auto Wreckers","10395 Scott Rd","Surrey","Bus graveyard",None,"10395 Scott Road, Surrey, BC"),
("4X09","Tunguska","Gravel pit, Seymour Demonstration Forest","Lower Seymour Conservation Reserve","North Vancouver","Russian gulag work camp",None,"Lower Seymour Conservation Reserve, North Vancouver, BC"),
("4X09","Tunguska","Viva Tower, suite 1708","1311 Howe St","Vancouver","Skinner's apartment and the balcony Krycek hangs from",None,"1311 Howe Street, Vancouver, BC"),
("4X09","Tunguska","200-block Northern Avenue","200-block Northern Ave","Vancouver","Flushing, Queens industrial street with the SWAT siege",None,"200 Northern Avenue, Vancouver, BC"),
("4X10","Terma","Stanley Park works yard","Off Pipeline Rd, Stanley Park","Vancouver","Russian prison camp, with 400 cubic feet of imported dirt",None,"Pipeline Road, Stanley Park, Vancouver, BC"),
("4X10","Terma","Cabin, Seymour Demonstration Forest","Lower Seymour Conservation Reserve","North Vancouver","Rural Russian family's home",None,"Lower Seymour Conservation Reserve, North Vancouver, BC"),
("4X10","Terma","Stokes gravel pit","South Surrey","Surrey","Alaskan forest oil well that explodes",None,"Stokes Pit, Surrey, BC"),
("4X11","El Mundo Gira","Squamish Nation gas bar","320 Seymour Blvd","North Vancouver","Truck stop",None,"320 Seymour Boulevard, North Vancouver, BC"),
("4X11","El Mundo Gira","Woodlands Hospital site","9 E. Columbia St","New Westminster","Lab, morgue and INS processing facility",None,"9 East Columbia Street, New Westminster, BC"),
("4X11","El Mundo Gira","Near Boundary Bay Airport","Boundary Bay","Delta","Migrant workers' camp",None,"Boundary Bay Airport, Delta, BC"),
("4X12","Kaddish","Winters Hotel","200 Abbott St","Vancouver","Weiss apartment exterior, copy shop and market interior",None,"200 Abbott Street, Vancouver, BC"),
("4X12","Kaddish","Shaughnessy Heights United Church","1550 W. 33rd Ave","Vancouver","The synagogue",None,"1550 West 33rd Avenue, Vancouver, BC"),
("4X13","Never Again","Samoo Pub","315 Carrall St","Vancouver","Hard Eight Lounge interior; exterior built in the alcove by the Army & Navy",None,"315 Carrall Street, Vancouver, BC"),
("4X13","Never Again","0-block West Cordova","0-block W. Cordova St","Vancouver","Philly Cheese Steak Shack and the Russian Market exteriors (built in parking lots); tattoo parlour at 45 W. Cordova",None,"45 West Cordova Street, Vancouver, BC"),
("4X13","Never Again","Only Stop convenience store","209 Abbott St","Vancouver","Russian Market interior",None,"209 Abbott Street, Vancouver, BC"),
("4X14","Leonard Betts","Woodlands Hospital site","9 E. Columbia St","New Westminster","Three Rivers and Allegheny hospitals, two labs",None,"9 East Columbia Street, New Westminster, BC"),
("4X14","Leonard Betts","Burrard St at Hastings St","Burrard St & W. Hastings St","Vancouver","The ambulance crash",None,"Burrard Street and West Hastings Street, Vancouver, BC"),
("4X15","Memento Mori","Woodlands Hospital site","9 E. Columbia St","New Westminster","Labs, Scully's hospital room, fertility clinic, incubator room, communications tunnel",None,"9 East Columbia Street, New Westminster, BC"),
("4X15","Memento Mori","Betsy Hagopian's house","Grand Blvd","North Vancouver","The MUFON house",None,"Grand Boulevard, North Vancouver, BC"),
("4X16","Unrequited","Jericho Park","4000-block W. 4th Ave","Vancouver","Vietnam War Memorial wall and grandstand",None,"Jericho Beach Park, Vancouver, BC"),
("4X16","Unrequited","Ballantyne Pier and CERES warehouse","655 Centennial Rd","Vancouver","Memorial wall night scenes, built inside the terminal",None,"Ballantyne Pier, Vancouver, BC"),
("4X16","Unrequited","Stanley Park pedestrian underpass","Georgia St at Stanley Park","Vancouver","Freedom Square and the military parade",None,"Stanley Park Causeway, Vancouver, BC"),
("4X16","Unrequited","Canada Place cruise ship terminal","999 Canada Place","Vancouver","Pentagon lobby",None,"999 Canada Place, Vancouver, BC"),
("4X17","Tempus Fugit","15 North Renfrew Restaurant","15 N. Renfrew St","Vancouver","Headless Woman Pub","Held over for Max.","15 North Renfrew Street, Vancouver, BC"),
("4X17","Tempus Fugit","London Guard Motel","2277 Kingsway","Vancouver","Paradise Motel: rooms 326, 330 and 331","Returned for The End.","2277 Kingsway, Vancouver, BC"),
("4X17","Tempus Fugit","Boundary Bay Airport and vicinity","7800 Alpha Way","Delta","Flight 549 crash site, hangar, runway and control tower",None,"Boundary Bay Airport, Delta, BC"),
("4X18","Max","Abbotsford Airport","30440 Liberator Ave","Abbotsford","Runway where the DC-6 nearly hits the sedan",None,"Abbotsford International Airport, Abbotsford, BC"),
("4X18","Max","15 North Renfrew Restaurant","15 N. Renfrew St","Vancouver","Headless Woman Pub",None,"15 North Renfrew Street, Vancouver, BC"),("4X21","Zero Sum","Mail-O-Matic","2720 S. Ingleton Ave","Burnaby","Transcontinental Express routing centre (also the sorting facility in Blood)",None,"2720 Ingleton Avenue, Burnaby, BC"),
("4X21","Zero Sum","Hotel Vancouver old boiler room","900 W. Georgia St","Vancouver","Incinerator room and the service elevator Skinner uses",None,"900 West Georgia Street, Vancouver, BC"),
("4X21","Zero Sum","Connaught Park playground","Connaught Park, W. 10th Ave at Larch St","Vancouver","Playground where the bees attack the children",None,"Connaught Park, Vancouver, BC"),
("4X22","Elegy","Thunderbird Lanes","120 W. 16th St","North Vancouver","Angie's Midnight Bowl",None,"120 West 16th Street, North Vancouver, BC"),
("4X23","Demons","Wisteria Cottage","18237 16 Ave","Surrey","The Rhode Island cottage where Mulder wakes up (also the old man's home in Travelers)",None,"18237 16 Avenue, Surrey, BC"),
("4X23","Demons","Cassandra house","3106 Alberta St","Vancouver","The Cassandra house (also the Sim house in Christmas Carol)",None,"3106 Alberta Street, Vancouver, BC"),
("4X24","Gethsemane","Dominion Directory (Yellow Pages)","4260 Still Creek Dr","Burnaby","DARPA industrial park, office building, parkade, bio-labs and stairwell",None,"4260 Still Creek Drive, Burnaby, BC"),
("4X24","Gethsemane","Vancouver Art Gallery rotunda","750 Hornby St","Vancouver","Smithsonian Institute spiral stairwell",None,"750 Hornby Street, Vancouver, BC"),
("4X24","Gethsemane","SBS Freezers","6228 Beresford St","Burnaby","Summit ice cave, warehouse and tent interiors (real cold)",None,"6228 Beresford Street, Burnaby, BC"),
("4X24","Gethsemane","Mount Seymour","Mount Seymour Rd","North Vancouver","Snowy mountain exteriors",None,"Mount Seymour Resort, North Vancouver, BC"),
("4X24","Gethsemane","Tantalus Range","Squamish","Squamish","Mountain aerials",None,"Tantalus Range, Squamish, BC"),
("2X03","Blood","Mail-O-Matic","2720 S. Ingleton Ave","Burnaby","Postal sorting facility",None,"2720 Ingleton Avenue, Burnaby, BC"),
]
