"""Season 5 (1997–98) locations from the location managers' book, pages 152–. (Partial; continued as read.)"""
ROWS = [
("5X01","Unusual Suspects","The Dominion Building","207 W. Hastings St","Vancouver","Baltimore newspaper office exterior",None,"207 West Hastings Street, Vancouver, BC"),
("5X01","Unusual Suspects","Robson Square Conference Centre","800 Robson St","Vancouver","Computer convention centre, lobby and foyer",None,"Robson Square, Vancouver, BC"),
("5X02","Redux","Justice Institute of B.C.","715 McBride Blvd","New Westminster","DARPA interior lobby and security booth",None,"715 McBride Boulevard, New Westminster, BC"),
("5X02","Redux","Fraserview Building, Woodlands","9 E. Columbia St","New Westminster","DARPA hallways for the walk-and-talk",None,"9 East Columbia Street, New Westminster, BC"),
("5X02","Redux","Dominion Directory (Yellow Pages)","4260 Still Creek Dr","Burnaby","DARPA exterior and lobby approach",None,"4260 Still Creek Drive, Burnaby, BC"),
("5X02","Redux","Open Learning Agency","4355 Mathissi Pl","Burnaby","Pentagon warehouse where Mulder finds the vial","Per the one-line schedule (Open Learning Institute).","4355 Mathissi Place, Burnaby, BC"),
("5X03","Redux II","Hastings Park Racecourse","188 N. Renfrew St","Vancouver","Racetrack where the Smoking Man meets the Elder",None,"Hastings Racecourse, Vancouver, BC"),
("5X03","Redux II","400-block West Cordova Street","400-block W. Cordova St","Vancouver","Georgetown street where the sniper watches Mulder and the Smoking Man; CSM's apartment window opposite the parkade",None,"420 West Cordova Street, Vancouver, BC"),
("5X03","Redux II","Atrium Inn stairwell","2889 E. Hastings St","Vancouver","Parkade stairwell the sniper climbs",None,"2889 East Hastings Street, Vancouver, BC"),
("5X03","Redux II","2-Jay's Café","81 W. Pender St","Vancouver","Diner where Mulder meets Samantha",None,"81 West Pender Street, Vancouver, BC"),
("5X04","Detour","Seymour Demonstration Forest","Lower Seymour Conservation Reserve","North Vancouver","Florida woods and highway (ten days of filming)",None,"Lower Seymour Conservation Reserve, North Vancouver, BC"),
("5X06","The Post-Modern Prometheus","Burrvilla, Deas Island Park","River Rd","Delta","Pollidori's house",None,"Deas Island Regional Park, Delta, BC"),
("5X06","The Post-Modern Prometheus","Maplewood Flats Wildlife Sanctuary","2600-block Dollarton Hwy","North Vancouver","The swale (scene cut)",None,"Maplewood Flats Conservation Area, North Vancouver, BC"),
("5X06","The Post-Modern Prometheus","Farm and barn","2981 41B St","Delta","The Berkowitz farm and the barn that burns (also used in Kill Switch)",None,"2981 41B Street, Delta, BC"),
("5X06","The Post-Modern Prometheus","Ladner Post Office","Delta St","Delta (Ladner)","Town riot",None,"Ladner Post Office, Delta, BC"),
("5X07","Emily","Glen Hospital","1036 Salsbury Dr","Vancouver","Retirement home (the brick apartment next door was Kurt's apartment in Memento Mori)",None,"1036 Salsbury Drive, Vancouver, BC"),
("5X05","Christmas Carol","Cassandra house","3106 Alberta St","Vancouver","The Sim house",None,"3106 Alberta Street, Vancouver, BC"),
("5X13","Patient X","Gravel pit, Seymour Demonstration Forest","Lower Seymour Conservation Reserve","North Vancouver","Kazakhstan forest where the Ladas burn",None,"Lower Seymour Conservation Reserve, North Vancouver, BC"),
("5X13","Patient X","Ruskin Dam","Wilson Rd","Mission (Ruskin)","Skyland Mountain dam where the crowd gathers and burns","Per the one-line schedule.","Ruskin Dam, Mission, BC"),
("5X14","The Red and the Black","Ruskin Dam","Wilson Rd","Mission (Ruskin)","The dam bridge and road after the burning","Per the one-line schedule.","Ruskin Dam, Mission, BC"),
("5X15","Travelers","Wisteria Cottage","18237 16 Ave","Surrey","The elderly Dales's rural house",None,"18237 16 Avenue, Surrey, BC"),
("5X15","Travelers","Meat Market building","1 W. Cordova St","Vancouver","The Hoot Owl bar",None,"1 West Cordova Street, Vancouver, BC"),
("5X18","The Pine Bluff Variant","2400 Court Motel","2400 Kingsway","Vancouver","Motor court where Mulder meets Haley",None,"2400 Kingsway, Vancouver, BC"),
("5X20","The End","London Guard Motel","2277 Kingsway","Vancouver","Motel",None,"2277 Kingsway, Vancouver, BC"),
("5X20","The End","General Motors Place","800 Griffiths Way","Vancouver","Sports arena for the chess match","Per the one-line schedule.","Rogers Arena, Vancouver, BC"),("5X08","Kitsunegari","George Pearson Hospital old boiler room","700 W. 57th Ave","Vancouver","Prison cafeteria (also Father Gregory's church in All Souls)",None,"George Pearson Centre, Vancouver, BC"),
("5X08","Kitsunegari","Great Outdoors","201 Lonsdale Ave","North Vancouver","Sporting goods store and the street chase",None,"201 Lonsdale Avenue, North Vancouver, BC"),
("5X09","Schizogeny","Hazelgrove Farm","Fort Langley","Langley","The hazelnut orchard and Lisa's clapboard farmhouse (night orchard scenes rebuilt on stage)",None,"Hazelgrove Farm, Fort Langley, BC"),
("5X10","Chinga","Shop Easy","2535 Shaughnessy St","Port Coquitlam","The supermarket",None,"2535 Shaughnessy Street, Port Coquitlam, BC"),
("5X10","Chinga","Save On Gas","North Vancouver","North Vancouver","Covered gas station where Scully fills up","Street not given.","North Vancouver, BC"),
("5X11","Kill Switch","Westham Island swing bridge","Westham Island Rd at Canoe Pass","Delta","Swing bridge where Esther throws the laptop","Built 1908.","Westham Island Bridge, Delta, BC"),
("5X11","Kill Switch","Read House","2981 41B St","Delta","Ruined farmhouse Mulder approaches",None,"2981 41B Street, Delta, BC"),
("5X11","Kill Switch","BFI Recycling back lot","Fraser River waterfront","Burnaby","Container-yard explosion (second unit)",None,"BFI Recycling, Burnaby, BC"),
("5X11","Kill Switch","Near Boundary Bay Airport","Boundary Bay","Delta","Trailer explosion in the clearing",None,"Boundary Bay Airport, Delta, BC"),
("5X13","Patient X","Ruskin Dam","Dewdney Trunk Rd","Mission (Ruskin)","Skyland Mountain dam, bridge and powerhouse where the abductees gather and burn",None,"Ruskin Dam, Mission, BC"),
("5X14","The Red and the Black","Stokes Pit","South Surrey","Surrey","UFO crash site",None,"Stokes Pit, Surrey, BC"),
("5X14","The Red and the Black","B.C. Parks works yard, base of Mount Seymour","Mount Seymour Rd","North Vancouver","Fort Wiekamp",None,"Mount Seymour Road, North Vancouver, BC"),
("5X16","Mind's Eye","Hastings Park Racecourse","188 N. Renfrew St","Vancouver","Atlantic City bus depot",None,"Hastings Racecourse, Vancouver, BC"),
("5X17","All Souls","St. Augustine's Parish","2028 W. 7th Ave","Vancouver","St. John's Church, Scully's church (exteriors)",None,"2028 West 7th Avenue, Vancouver, BC"),
("5X17","All Souls","George Pearson Hospital old boiler room","700 W. 57th Ave","Vancouver","Father Gregory's church",None,"George Pearson Centre, Vancouver, BC"),
("5X17","All Souls","The Kernoff house","500-block E. 12th St","North Vancouver","The Kernoff house",None,"500 East 12th Street, North Vancouver, BC"),
("5X18","The Pine Bluff Variant","Dunbar Theatre","4555 Dunbar St","Vancouver","Vogue Theatre",None,"4555 Dunbar Street, Vancouver, BC"),
("5X18","The Pine Bluff Variant","Mulder's apartment (new exterior)","1010 Salsbury St","Vancouver","Mulder's apartment exterior, after the York St building priced itself out",None,"1010 Salsbury Drive, Vancouver, BC"),
("5X18","The Pine Bluff Variant","Former Bank of Canada building","900 W. Hastings St","Vancouver","The bank robbery; Mulder's drive-up on the Hornby St side",None,"900 West Hastings Street, Vancouver, BC"),
("5X19","Folie à Deux","The Starn house","500-block E. 11th St","North Vancouver","Gary Lambert's house with the monster on the roof",None,"500 East 11th Street, North Vancouver, BC"),
("5X19","Folie à Deux","Vinylright","12340 Horseshoe Way","Richmond","VinylRight exterior; the armoured car and the hostage siege",None,"12340 Horseshoe Way, Richmond, BC"),
("5X20","The End","Crease Clinic, Riverview Hospital","2601 Lougheed Hwy","Coquitlam","The final shooting day; psychiatric hospital",None,"Riverview Hospital, Coquitlam, BC"),
]
