#!/usr/bin/env python3
from browse_navigation import navigation, ASSET as NAV_ASSET
"""Build the transcript season index and live episode galleries."""

from pathlib import Path
from transcript_header import HEADER, ASSETS


SEASON_1 = [
    ("pilot", "Pilot", "1X79", "Mulder and Scully’s first investigation, organized scene by scene for research and close reading."),
    ("deep-throat", "Deep Throat", "1X01", "A missing test pilot draws the agents toward Ellens Air Base and a secret informant."),
    ("squeeze", "Squeeze", "1X02", "An impossible murder case brings the agents face to face with Eugene Victor Tooms."),
    ("conduit", "Conduit", "1X03", "A girl’s disappearance forces Mulder to confront the memory of his own sister."),
    ("jersey-devil", "The Jersey Devil", "1X04", "A body in the woods leads Mulder toward a creature beyond Atlantic City."),
    ("shadows", "Shadows", "1X05", "An unseen force appears to protect a grieving secretary from danger."),
    ("ghost-in-the-machine", "Ghost in the Machine", "1X06", "A lethal artificial intelligence turns a high-rise office into a system of traps."),
    ("ice", "Ice", "1X07", "Isolation and suspicion consume an Arctic research team after a discovery in the ice."),
    ("space", "Space", "1X08", "A shuttle mission is threatened by sabotage and an astronaut’s encounter in orbit."),
    ("fallen-angel", "Fallen Angel", "1X09", "A secret military recovery operation draws Mulder to a crash site and Max Fenig."),
    ("eve", "Eve", "1X10", "Two identical girls and two identical murders expose a genetics experiment."),
    ("fire", "Fire", "1X11", "A dangerous arsonist and a figure from Mulder’s past ignite a combustible case."),
    ("beyond-the-sea", "Beyond the Sea", "1X12", "In the midst of grief, Scully confronts a death-row inmate who claims psychic powers."),
    ("gender-bender", "Gender Bender", "1X13", "A series of intimate deaths points toward an isolated community with a secret."),
    ("lazarus", "Lazarus", "1X14", "Scully’s former partner becomes connected to a bank robber after a near-fatal shooting."),
    ("young-at-heart", "Young at Heart", "1X15", "A criminal Mulder helped imprison appears to return years later without having aged."),
    ("ebe", "E.B.E.", "1X16", "A UFO recovery trail pulls Mulder and Scully into a campaign of disinformation."),
    ("miracle-man", "Miracle Man", "1X17", "A young faith healer becomes the center of a series of mysterious deaths."),
    ("shapes", "Shapes", "1X18", "A Montana killing reopens one of the FBI’s earliest unexplained cases."),
    ("darkness-falls", "Darkness Falls", "1X19", "An ancient swarm traps a logging crew and the agents in a remote forest."),
    ("tooms", "Tooms", "1X20", "Eugene Victor Tooms returns, placing Scully in danger as Mulder races to stop him."),
    ("born-again", "Born Again", "1X21", "A child’s impossible knowledge connects a murder investigation to a detective’s death."),
    ("roland", "Roland", "1X22", "A laboratory death draws the agents toward a gifted caretaker and a hidden connection."),
    ("the-erlenmeyer-flask", "The Erlenmeyer Flask", "1X23", "Deep Throat leads Mulder and Scully toward evidence that could prove everything."),
]

SEASON_2 = [
    ("little-green-men", "Little Green Men", "2X01", "Separated from the X-Files, Mulder follows a signal to an abandoned observatory in Puerto Rico."),
    ("the-host", "The Host", "2X02", "A body in the sewers leads Mulder to a parasitic creature and an unexpected ally."),
    ("blood", "Blood", "2X03", "Electronic messages push ordinary residents toward violence in a quiet Pennsylvania town."),
    ("sleepless", "Sleepless", "2X04", "A group of Vietnam veterans who no longer sleep becomes the center of a deadly conspiracy."),
    ("duane-barry", "Duane Barry", "2X05", "A hostage crisis brings Mulder face to face with a man who says he has been abducted."),
    ("ascension", "Ascension", "2X06", "Mulder follows Duane Barry to Skyland Mountain in a desperate search for Scully."),
    ("3", "3", "2X07", "Alone in Los Angeles, Mulder investigates a series of murders linked to a thirst for blood."),
    ("one-breath", "One Breath", "2X08", "Scully returns in critical condition as Mulder searches for answers and a way to help her."),
    ("firewalker", "Firewalker", "2X09", "A volcanic research team's discovery draws Mulder and Scully into a deadly quarantine."),
    ("red-museum", "Red Museum", "2X10", "Strange abductions in a Wisconsin town lead the agents toward a secret experiment."),
    ("excelsis-dei", "Excelsis Dei", "2X11", "An assault at a care home leads Mulder and Scully to investigate its unseen residents."),
    ("aubrey", "Aubrey", "2X12", "A detective's disturbing visions uncover a connection to murders committed decades earlier."),
    ("irresistible", "Irresistible", "2X13", "A grave desecration case brings the agents face to face with a deeply unsettling killer."),
    ("die-hand-die-verletzt", "Die Hand Die Verletzt", "2X14", "A teenager's death exposes a school's secrets and a sinister substitute teacher."),
    ("fresh-bones", "Fresh Bones", "2X15", "Deaths at a refugee camp lead Mulder and Scully into a case of abuse and apparent voodoo."),
    ("colony", "Colony", "2X16", "Identical murder victims and a visitor from Mulder's past draw the agents into a dangerous pursuit."),
    ("end-game", "End Game", "2X17", "A hostage exchange sends Mulder north in pursuit of the alien bounty hunter."),
    ("fearful-symmetry", "Fearful Symmetry", "2X18", "Missing zoo animals and impossible attacks lead the agents to a mysterious pattern."),
    ("dod-kalm", "Død Kalm", "2X19", "Mulder and Scully board a deserted ship whose remaining crew have aged overnight."),
    ("humbug", "Humbug", "2X20", "A murder investigation brings the agents to a Florida community of sideshow performers."),
    ("the-calusari", "The Calusari", "2X21", "A family tragedy draws Mulder and Scully toward a child's unsettling connection to an unseen force."),
    ("f-emasculata", "F. Emasculata", "2X22", "An escaped-prisoner search exposes a deadly outbreak and a concealed experiment."),
    ("soft-light", "Soft Light", "2X23", "A physicist's shadow becomes the focus of a series of unexplained disappearances."),
    ("our-town", "Our Town", "2X24", "A missing inspector leads the agents into a poultry town with a horrifying secret."),
    ("anasazi", "Anasazi", "2X25", "Stolen government records send Mulder and Scully toward a buried discovery in New Mexico."),
]

SEASON_3 = [
    ("the-blessing-way", "The Blessing Way", "3X01", "As Mulder fights to survive, Scully confronts the consequences of the stolen files."),
    ("paper-clip", "Paper Clip", "3X02", "A hidden archive draws Mulder and Scully deeper into the origins of the conspiracy."),
    ("dpo", "D.P.O.", "3X03", "A string of unusual deaths leads the agents to a young man with a dangerous electrical charge."),
    ("clyde-bruckmans-final-repose", "Clyde Bruckman’s Final Repose", "3X04", "A reluctant psychic helps investigate murders while confronting the certainty of death."),
    ("the-list", "The List", "3X05", "An executed prisoner’s promise of revenge haunts the people inside a Florida prison."),
    ("2shy", "2Shy", "3X06", "An online predator leaves a trail of victims with an inexplicable loss of body fat."),
    ("the-walk", "The Walk", "3X07", "A military hospital’s mysterious attacks point toward a wounded veteran’s unseen reach."),
    ("oubliette", "Oubliette", "3X08", "A kidnapped teenager’s ordeal appears to be shared by a woman who escaped a similar captivity."),
    ('nisei', 'Nisei', '3X09', 'An alien autopsy tape leads Mulder to a secret train and Scully to a group of fellow abductees.'),
    ('731', '731', '3X10', 'Mulder is trapped aboard a train while Scully searches for the truth behind a covert experiment.'),
    ('revelations', 'Revelations', '3X11', 'A boy with mysterious wounds puts Scully’s faith at the center of a dangerous case.'),
    ('war-of-the-coprophages', 'War of the Coprophages', '3X12', 'A rash of deaths and reports of killer cockroaches send a small town into panic.'),
    ('syzygy', 'Syzygy', '3X13', 'Two teenage friends and an unusual planetary alignment unsettle a town and the agents.'),
    ('grotesque', 'Grotesque', '3X14', 'A serial killer’s disturbing drawings pull Mulder deep into an investigation led by his former mentor.'),
    ('piper-maru', 'Piper Maru', '3X15', 'A salvage crew’s radiation exposure reveals a mystery beneath the Pacific.'),
    ('apocrypha', 'Apocrypha', '3X16', 'The search for Krycek connects a recovered vessel, a stolen tape, and the attack on Skinner.'),
    ('pusher', 'Pusher', '3X17', 'A man who can bend others to his will draws Mulder into a deadly contest.'),
    ('teso-dos-bichos', 'Teso Dos Bichos', '3X18', 'Deaths at a museum follow the arrival of an ancient burial urn from Ecuador.'),
    ('hell-money', 'Hell Money', '3X19', 'A series of deaths in San Francisco’s Chinatown exposes a deadly underground lottery.'),
    ('jose-chungs-from-outer-space', 'Jose Chung’s From Outer Space', '3X20', 'A writer interviews Scully about an alien abduction case full of contradictory accounts.'),
    ('avatar', 'Avatar', '3X21', 'Skinner becomes a murder suspect as a mysterious woman haunts his waking life.'),
    ('quagmire', 'Quagmire', '3X22', 'Deaths near a Georgia lake send Mulder and Scully searching for a legendary creature.'),
    ('wetwired', 'Wetwired', '3X23', 'A strange television signal fuels paranoia and threatens Scully’s trust in Mulder.'),
    ('talitha-cumi', 'Talitha Cumi', '3X24', 'A mysterious healer offers answers as Mulder’s mother falls critically ill.'),
]

SEASON_4 = [('herrenvolk', 'Herrenvolk', '4X01', 'A mysterious healer leads Mulder toward a hidden operation as Scully searches for answers.'), ('home', 'Home', '4X03', 'An isolated family conceals a horrifying secret in a small Pennsylvania town.'), ('teliko', 'Teliko', '4X04', 'A series of disappearances draws the agents toward a suspect with an unusual condition.'), ('unruhe', 'Unruhe', '4X02', 'Distorted photographs offer clues to a kidnapper’s terrifying delusions.'), ('the-field-where-i-died', 'The Field Where I Died', '4X05', 'An investigation into a religious compound stirs memories of possible past lives.'), ('sanguinarium', 'Sanguinarium', '4X06', 'Strange deaths at a hospital lead the agents to suspect a sinister influence.'), ('musings-of-a-cigarette-smoking-man', 'Musings of a Cigarette-Smoking Man', '4X07', 'Frohike recounts the possible hidden history of the Cigarette-Smoking Man.'), ('tunguska', 'Tunguska', '4X09', 'A diplomatic courier’s mysterious cargo sends Mulder and Krycek to Russia.'), ('terma', 'Terma', '4X10', 'Scully faces a Senate inquiry while Mulder tries to escape a secret experiment.'), ('paper-hearts', 'Paper Hearts', '4X08', 'A disturbing dream draws Mulder back to a convicted child killer and his victims.')]

SEASON_4 += [('never-again', 'Never Again', '4X13', 'Scully’s solo trip to Philadelphia brings her into the life of a man haunted by his tattoo.'), ('memento-mori', 'Memento Mori', '4X15', 'A devastating diagnosis leads Scully and Mulder back to the women connected to her abduction.'), ('kaddish', 'Kaddish', '4X12', 'A murder investigation in Brooklyn turns toward grief, revenge, and the legend of the golem.'), ('unrequited', 'Unrequited', '4X16', 'A seemingly invisible Vietnam veteran targets the military leaders he believes abandoned him.'), ('tempus-fugit', 'Tempus Fugit', '4X17', 'A plane crash brings Max Fenig back into the agents’ investigation of alien abductions.'), ('max', 'Max', '4X18', 'The search for the cause of Flight 549’s crash leads Mulder toward a dangerous piece of evidence.'), ('synchrony', 'Synchrony', '4X19', 'A mysterious older man seems to know exactly when fatal events will occur.'), ('small-potatoes', 'Small Potatoes', '4X20', 'A series of unusual births leads the agents to a man who can take on other people’s appearances.'), ('zero-sum', 'Zero Sum', '4X21', 'Skinner conceals evidence after making a desperate bargain to help Scully.'), ('elegy', 'Elegy', '4X22', 'Apparitions of murdered women lead the agents to a bowling alley and a psychiatric center.'), ('demons', 'Demons', '4X23', 'Mulder wakes with missing memories and evidence that connects him to two deaths.'), ('gethsemane', 'Gethsemane', '4X24', 'A discovery in the Canadian mountains tests Mulder’s beliefs and Scully’s trust in the evidence.')]

SEASON_4.insert(10, ('el-mundo-gira', 'El Mundo Gira', '4X11', 'A mysterious death at a migrant workers’ camp leads Mulder and Scully to reports of El Chupacabra.'))

SEASON_4.insert(11, ('leonard-betts', 'Leonard Betts', '4X14', 'A missing body leads the agents to a paramedic with a remarkable ability to regenerate.'))

SEASON_4_EPISODE_NUMBERS = {'herrenvolk': 1, 'home': 2, 'teliko': 3, 'unruhe': 4, 'the-field-where-i-died': 5, 'sanguinarium': 6, 'musings-of-a-cigarette-smoking-man': 7, 'tunguska': 8, 'terma': 9, 'paper-hearts': 10, 'el-mundo-gira': 11, 'leonard-betts': 12, 'never-again': 13, 'memento-mori': 14, 'kaddish': 15, 'unrequited': 16, 'tempus-fugit': 17, 'max': 18, 'synchrony': 19, 'small-potatoes': 20, 'zero-sum': 21, 'elegy': 22, 'demons': 23, 'gethsemane': 24}

SEASON_5 = [('redux', 'Redux', '5X02', 'Mulder challenges the evidence behind the conspiracy as Scully searches for a cure.'), ('redux-ii', 'Redux II', '5X03', 'Scully’s condition worsens while Mulder faces a choice about whom to trust.'), ('unusual-suspects', 'Unusual Suspects', '5X01', 'The Lone Gunmen recall the Baltimore case that brought them together with Mulder.'), ('detour', 'Detour', '5X04', 'A detour through a Florida forest leads the agents to an elusive predator.'), ('the-post-modern-prometheus', 'The Post-Modern Prometheus', '5X06', 'A strange encounter in a small town draws the agents into a story of science and loneliness.'), ('christmas-carol', 'Christmas Carol', '5X05', 'A mysterious phone call leads Scully to a little girl with a familiar face.'), ('emily', 'Emily', '5X07', 'Scully fights to protect Emily as Mulder investigates the circumstances of her birth.'), ('kitsunegari', 'Kitsunegari', '5X08', 'Robert Modell escapes custody, drawing the agents into another battle of perception.'), ('schizogeny', 'Schizogeny', '5X09', 'A teenager’s troubled family life becomes entangled with mysterious deaths in an orchard.'), ('chinga', 'Chinga', '5X10', 'Scully’s vacation in Maine turns into an investigation of a dangerous doll.'), ('kill-switch', 'Kill Switch', '5X11', 'A computer programmer’s death leads the agents to an artificial intelligence defending its survival.'), ('bad-blood', 'Bad Blood', '5X12', 'Mulder and Scully offer very different accounts of a vampire investigation in Texas.'), ('patient-x', 'Patient X', '5X13', 'A group of abductees draws the agents toward a new threat within the conspiracy.'), ('the-red-and-the-black', 'The Red and the Black', '5X14', 'The aftermath of a mass burning raises questions about resistance and the abductees’ memories.'), ('travelers', 'Travelers', '5X15', 'Arthur Dales recounts an early X-File and a secret hidden in the McCarthy era.'), ('minds-eye', "Mind's Eye", '5X16', 'A blind woman becomes a murder suspect after displaying impossible knowledge of the crime.')]

SEASON_5 += [('all-souls', 'All Souls', '5X17', 'The deaths of four girls draw Scully into a case that tests her faith and her grief.'), ('the-pine-bluff-variant', 'The Pine Bluff Variant', '5X18', 'Scully suspects Mulder is hiding something as he infiltrates a group planning a biological attack.'), ('folie-a-deux', 'Folie à Deux', '5X19', 'A hostage crisis leaves Mulder seeing a threat that no one else believes is real.'), ('the-end', 'The End', '5X20', 'A gifted young chess player brings Diana Fowley into the case as the X-Files faces a devastating threat.')]

SEASON_6 = [('the-beginning', 'The Beginning', '6ABX01', 'An alien creature draws Mulder and Scully back into a case they are forbidden to investigate.'), ('drive', 'Drive', '6ABX02', 'A desperate man forces Mulder westward while Scully searches for the cause of his illness.'), ('triangle', 'Triangle', '6ABX03', 'Mulder boards a ship in the Bermuda Triangle and finds himself in 1939.'), ('dreamland', 'Dreamland', '6ABX04', 'An encounter near Area 51 leaves Mulder living another man’s life.'), ('dreamland-ii', 'Dreamland II', '6ABX05', 'Mulder and Morris Fletcher struggle with the consequences of their switched identities.'), ('how-the-ghosts-stole-christmas', 'How the Ghosts Stole Christmas', '6ABX08', 'A Christmas Eve visit to a haunted house becomes a test of the agents’ trust.'), ('terms-of-endearment', 'Terms of Endearment', '6ABX06', 'A missing baby leads Mulder and Scully to a father with a secret.'), ('the-rain-king', 'The Rain King', '6ABX07', 'A Kansas town’s unusual weather draws the agents into a complicated romance.'), ('sr-819', 'S.R. 819', '6ABX10', 'Skinner falls gravely ill as a mysterious caller threatens his life.'), ('tithonus', 'Tithonus', '6ABX09', 'Scully investigates a photographer who seems to know when people will die.'), ('two-fathers', 'Two Fathers', '6ABX11', 'Cassandra Spender returns with knowledge that threatens the conspiracy.'), ('one-son', 'One Son', '6ABX12', 'The agents confront the final preparations for alien colonization.'), ('agua-mala', 'Agua Mala', '6ABX14', 'A hurricane traps Mulder and Scully with a creature that travels through water.'), ('monday', 'Monday', '6ABX15', 'A bank robbery forces the agents to relive the same deadly day.'), ('arcadia', 'Arcadia', '6ABX13', 'Mulder and Scully pose as a married couple in a community with strict rules.'), ('alpha', 'Alpha', '6ABX16', 'A rare animal’s arrival leads to a series of killings and a disputed identity.'), ('trevor', 'Trevor', '6ABX17', 'An escaped prisoner appears able to pass through solid objects.'), ('milagro', 'Milagro', '6ABX18', 'A writer living next to Mulder becomes entangled in a murder investigation.'), ('the-unnatural', 'The Unnatural', '6ABX19', 'A baseball story leads Mulder to an extraordinary player from the past.'), ('three-of-a-kind', 'Three of a Kind', '6ABX20', 'The Lone Gunmen call Scully to Las Vegas after Byers spots Susanne Modeski.'), ('field-trip', 'Field Trip', '6ABX21', 'A missing couple leads the agents into a cave and a series of deceptive realities.'), ('biogenesis', 'Biogenesis', '6ABX22', 'An artifact from the African coast has a disturbing effect on Mulder.')]

SEASON_7 = [('the-sixth-extinction', 'The Sixth Extinction', '7ABX03', 'Scully studies the mysterious craft in Africa while Mulder struggles with an overwhelming new ability.'), ('the-sixth-extinction-ii-amor-fati', 'The Sixth Extinction II: Amor Fati', '7ABX04', 'As Scully searches for Mulder, he experiences a life shaped by the Cigarette-Smoking Man.'), ('hungry', 'Hungry', '7ABX01', 'A fast-food worker struggles to control a hunger that makes him the focus of an investigation.'), ('millennium', 'Millennium', '7ABX05', 'The agents turn to Frank Black when missing bodies point to a plan for the new millennium.'), ('rush', 'Rush', '7ABX06', 'A murder investigation leads to teenagers who can move faster than the eye can see.'), ('the-goldberg-variation', 'The Goldberg Variation', '7ABX02', 'A man with extraordinary luck draws the agents into a dangerous chain of coincidences.'), ('orison', 'Orison', '7ABX07', 'Donnie Pfaster escapes prison and brings Scully face to face with an old terror.'), ('the-amazing-maleeni', 'The Amazing Maleeni', '7ABX08', 'A magician’s death leads Mulder and Scully through a series of elaborate misdirections.'), ('signs-and-wonders', 'Signs and Wonders', '7ABX09', 'Deaths involving snakes draw the agents into a divided religious community.'), ('sein-und-zeit', 'Sein und Zeit', '7ABX10', 'A missing girl’s case brings Mulder’s search for Samantha into painful focus.'), ('closure', 'Closure', '7ABX11', 'Mulder follows new leads toward the truth about his sister’s disappearance.'), ('x-cops', 'X-Cops', '7ABX12', 'A television crew follows the agents and local deputies as they investigate a changing threat.'), ('first-person-shooter', 'First Person Shooter', '7ABX13', 'A death inside a virtual-reality game brings the agents and the Lone Gunmen into the action.'), ('theef', 'Theef', '7ABX14', 'A doctor’s family becomes the target of a man using folk magic to seek revenge.'), ('en-ami', 'En Ami', '7ABX15', 'The Cigarette-Smoking Man offers Scully a chance to obtain a life-saving discovery.'), ('chimera', 'Chimera', '7ABX16', 'Mulder investigates a disappearance in a seemingly idyllic town while Scully maintains a stakeout.'), ('all-things', 'all things', '7ABX17', 'A chance encounter makes Scully reconsider a past relationship and the choices that brought her here.'), ('brand-x', 'Brand X', '7ABX19', 'A witness’s death leads the agents to a tobacco company and an unusual infestation.'), ('hollywood-ad', 'Hollywood A.D.', '7ABX18', 'A case involving a forged religious artifact inspires a Hollywood version of the agents’ lives.'), ('fight-club', 'Fight Club', '7ABX20', 'Two identical women leave a trail of violent encounters wherever their paths cross.'), ('je-souhaite', 'Je Souhaite', '7ABX21', 'The discovery of a genie leads Mulder and Scully through wishes with unexpected consequences.'), ('requiem', 'Requiem', '7ABX22', 'A return to Bellefleur brings the agents back to their first case and a new series of disappearances.')]

SEASON_8 = [('within', 'Within', '8ABX01', 'Scully and Skinner search for Mulder as John Doggett takes charge of the investigation.'), ('without', 'Without', '8ABX02', 'The search for Mulder leads to Gibson Praise and a shape-shifting threat.'), ('patience', 'Patience', '8ABX04', 'Scully and Doggett investigate killings linked to a creature that has waited decades for revenge.'), ('roadrunners', 'Roadrunners', '8ABX05', 'Scully becomes trapped in a remote community with a terrifying secret.'), ('invocation', 'Invocation', '8ABX06', 'A missing boy returns ten years later without having aged.'), ('redrum', 'Redrum', '8ABX03', 'A man accused of murder experiences the days leading to the crime in reverse.'), ('via-negativa', 'Via Negativa', '8ABX07', 'A cult investigation draws Doggett into a nightmare he cannot escape.'), ('surekill', 'Surekill', '8ABX09', 'A shooting leads the agents to two brothers with extraordinary vision.'), ('salvage', 'Salvage', '8ABX10', 'A man believed dead returns with a body that is transforming into metal.'), ('badlaa', 'Badlaa', '8ABX12', 'Mysterious deaths lead Scully and Doggett to a man who can alter what people see.'), ('the-gift', 'The Gift', '8ABX11', 'Doggett follows an old case of Mulder’s to a town hiding a creature with unusual healing powers.'), ('medusa', 'Medusa', '8ABX13', 'A deadly organism traps Doggett and a rescue team in Boston’s subway tunnels.'), ('per-manum', 'Per Manum', '8ABX08', 'A disturbing account of an alien pregnancy raises questions about Scully’s own situation.'), ('this-is-not-happening', 'This Is Not Happening', '8ABX14', 'A returned abductee gives the agents new hope of finding Mulder.'), ('deadalive', 'DeadAlive', '8ABX15', 'Mulder’s return forces Scully and Skinner to confront an unexpected medical crisis.'), ('three-words', 'Three Words', '8ABX18', 'Mulder’s search for answers puts him at odds with Doggett over a suspicious source.'), ('empedocles', 'Empedocles', '8ABX17', 'Reyes asks Mulder to investigate a case connected to the death of Doggett’s son.'), ('vienen', 'Vienen', '8ABX16', 'Mulder and Doggett encounter the black oil aboard an offshore drilling platform.'), ('alone', 'Alone', '8ABX19', 'Doggett and a new partner disappear while investigating a deadly creature.'), ('essence', 'Essence', '8ABX20', 'Scully’s approaching due date brings new threats from within the conspiracy.'), ('existence', 'Existence', '8ABX21', 'The agents work to protect Scully and her baby as their enemies close in.')]

SEASONS = {1: SEASON_1, 2: SEASON_2, 3: SEASON_3, 4: SEASON_4, 5: SEASON_5, 6: SEASON_6, 7: SEASON_7, 8: SEASON_8}

HEAD = '''<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=DM+Mono:wght@300;400;500&family=Libre+Caslon+Display&family=Oswald:wght@300;400;500;600&display=swap" rel="stylesheet">'''



BASE = '''*{box-sizing:border-box}html{background:#08100d;color:#eeeee8}body{margin:0;font:400 15px/1.7 "DM Mono",monospace;background:#08100d}a{color:inherit;text-decoration:none}.shell{width:min(1656px,calc(100% - 56px));margin:auto}header{border-bottom:1px solid #343c38;position:relative;z-index:5;background:#08100d}.shell nav{}.brand{font:500 1.18rem/1 "Oswald",sans-serif;letter-spacing:.08em;white-space:nowrap}.brand .x{display:inline-block;color:#e44238;margin:0 .13em}.links{display:flex;gap:26px;align-items:center;font-size:.58rem;text-transform:uppercase;letter-spacing:.12em}.links a{color:#929c95}.links a:hover,.links .active{color:#eeeee8}header nav{height:82px;display:flex;align-items:center;justify-content:space-between}.eyebrow{color:#e44238;font-size:.6rem;letter-spacing:.19em;text-transform:uppercase}.hero{padding:92px 0 76px;border-bottom:1px solid #343c38}.crumb{font-size:.58rem;text-transform:uppercase;letter-spacing:.12em;color:#818b84;margin-bottom:30px}.crumb a{color:#eeeee8}.hero h1{font:400 clamp(4.4rem,9vw,9.2rem)/.84 "Oswald",sans-serif;text-transform:uppercase;letter-spacing:-.035em;margin:0}.hero p{color:#a2aaa4;max-width:760px;margin:30px 0 0;font-size:.85rem;line-height:1.85}.summary{display:flex;gap:1px;background:#343c38;border:1px solid #343c38;width:max-content;margin-top:48px}.stat{background:#0e1412;padding:19px 26px;min-width:150px}.stat b{display:block;font:400 1.65rem/1 "Oswald",sans-serif}.stat span{display:block;color:#7f8982;font-size:.5rem;letter-spacing:.12em;text-transform:uppercase;margin-top:10px}footer{border-top:1px solid #343c38;margin-top:90px;padding:38px 0;color:#7f8982;font-size:.55rem;letter-spacing:.11em;text-transform:uppercase}.footer-row{display:flex;justify-content:space-between}@media(max-width:920px){.links{display:none}.hero{padding-top:64px}.shell{width:min(100% - 32px,1656px)}}'''


def season_landing() -> str:
    cards=[]
    for season in range(1,10):
        live=season in SEASONS
        count=len(SEASONS.get(season, []))
        image="pilot" if season == 1 else "the-blessing-way" if season == 3 else "herrenvolk" if season == 4 else "redux" if season == 5 else "the-beginning" if season == 6 else "the-sixth-extinction" if season == 7 else "within" if season == 8 else "little-green-men"
        image_ext="jpg" if season >= 3 else "webp"
        cards.append(f'''<a class="season-card {'live' if live else 'soon'}" href="/transcripts/season-{season}/">
          <div class="season-visual"><span>{season:02d}</span>{f'<img src="/assets/transcript-stills/{image}.{image_ext}" alt="Scene from Season {season}">' if live else ''}</div>
          <div class="season-copy"><div><span class="eyebrow">{f'{count} transcripts live' if live else 'Collection pending'}</span><h2>Season {season}</h2></div><b>{'Explore season →' if live else 'Coming soon →'}</b></div></a>''')
    return f'''<!doctype html><html lang="en"><head><title>Transcripts - Boggsfiles</title><meta name="description" content="Browse character-labelled X-Files episode transcripts by season.">{HEAD}<style>{BASE}
    .transcript-landing .shell{{width:min(1200px,calc(100% - 48px))}}@media(max-width:560px){{.transcript-landing .shell{{width:calc(100% - 28px)}}}}.seasons{{padding:72px 0 0}}.season-grid{{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1px;background:#343c38;border:1px solid #343c38}}.season-card{{background:#0e1412;min-height:390px;display:flex;flex-direction:column;transition:.2s}}.season-card:hover{{background:#131a17}}.season-visual{{height:235px;position:relative;overflow:hidden;background:#111714}}.season-visual img{{width:100%;height:100%;object-fit:cover;filter:saturate(.78) brightness(.72);transition:.3s}}.season-card:hover img{{transform:scale(1.02)}}.season-visual>span{{position:absolute;right:20px;bottom:-30px;font:500 9rem/1 "Oswald",sans-serif;color:#1b231f;z-index:1}}.season-visual img+span{{display:none}}.season-copy{{padding:28px 30px 32px;display:flex;align-items:end;justify-content:space-between;gap:20px;flex:1}}.season-copy h2{{font:400 2.8rem/1 "Oswald",sans-serif;text-transform:uppercase;margin:8px 0 0}}.season-copy>b{{font-size:.55rem;text-transform:uppercase;letter-spacing:.12em;white-space:nowrap}}.soon{{color:#929c95}}@media(max-width:1000px){{.season-grid{{grid-template-columns:repeat(2,1fr)}}}}@media(max-width:620px){{.season-grid{{grid-template-columns:1fr}}.season-copy{{align-items:start;flex-direction:column}}}}
    </style>{ASSETS}</head><body class="transcript-landing">{HEADER}<main><section class="hero"><div class="shell"><div class="crumb"><a href="/archive/">Archive</a> &nbsp;/&nbsp; Transcripts</div><div class="eyebrow">The aired record</div><h1>Transcripts</h1><p>Character-labelled episode dialogue prepared from the official DVD subtitle tracks, organized by season and designed for searching, reference, and close reading.</p><div class="summary"><div class="stat"><b>9</b><span>Seasons</span></div><div class="stat"><b>{sum(len(episodes) for episodes in SEASONS.values())}</b><span>Transcripts live</span></div><div class="stat"><b>DVD</b><span>Subtitle source</span></div></div></div></section><section class="seasons"><div class="shell"><div class="season-grid">{''.join(cards)}</div></div></section></main><footer><div class="shell footer-row">BOGGSFILES · TRANSCRIPT ARCHIVE <span><a href="/">Home</a> · <a href="/archive/">Archive</a></span></div></footer></body></html>'''


def season_page(season: int, episodes: list[tuple[str, str, str, str]]) -> str:
    cards=[]
    display_episodes=list(episodes)
    if season == 4 and not any(ep[0] == 'leonard-betts' for ep in episodes):
        display_episodes.append(('leonard-betts', 'Leonard Betts', '4X14', 'Transcript coming soon.'))
        display_episodes.sort(key=lambda ep: SEASON_4_EPISODE_NUMBERS[ep[0]])
    for number,(slug,title,code,description) in enumerate(display_episodes,1):
        if season == 4: number = SEASON_4_EPISODE_NUMBERS[slug]
        pending = (slug == 'leonard-betts' and not any(ep[0] == slug for ep in episodes))
        opening = '<article class="episode-card pending-transcript">' if pending else f'<a class="episode-card" href="/transcripts/season-{season}/{slug}/">'
        closing = '</article>' if pending else '</a>'
        cards.append(f'''{opening}<img src="/assets/transcript-stills/{slug}.{'jpg' if season > 2 or season == 2 and number > 4 else 'webp'}" alt="Scene from {title}" loading="lazy"><div class="episode-copy"><span>File {number:02d} · {code}</span><h2>{title}</h2><p>{description}</p><b>{'Coming soon' if pending else 'Read transcript →'}</b></div>{closing}''')

    years = "1993–1994" if season == 1 else "1994–1995" if season == 2 else "1996–1997" if season == 4 else "1997–1998" if season == 5 else "1998–1999" if season == 6 else "1999–2000" if season == 7 else "2000–2001" if season == 8 else "1995–1996"
    intro = "The beginning of the X-Files and the beginning of Mulder and Scully." if season == 1 else "The X-Files is closed, but the search continues as Mulder and Scully are pulled back toward the cases that defined them."
    if season in (3,4,5,6,7,8):
        intro = "Mulder and Scully pursue the conspiracy and investigate a new collection of unexplained cases."
    total = 21 if season == 8 else 22 if season in (6,7) else 20 if season == 5 else 25 if season == 2 else 24
    source_index = "first-season-index.html" if season == 1 else "second-season-index.html" if season == 2 else "fourth-season-index.html" if season == 4 else "fifth-season-index.html" if season == 5 else "third-season-index.html"
    return f'''<!doctype html><html lang="en"><head><title>Season {season} Transcripts - Boggsfiles</title><meta name="description" content="Browse character-labelled transcripts for The X-Files Season {season}.">{HEAD}<style>{BASE}
    .episodes{{padding:72px 0 0}}.season-head{{display:flex;justify-content:space-between;align-items:end;margin-bottom:34px}}.season-head h2{{font:400 clamp(3.2rem,6vw,6rem)/.9 "Oswald",sans-serif;text-transform:uppercase;margin:10px 0 0}}.season-head>span{{color:#8c968f;font-size:.62rem;letter-spacing:.12em;text-transform:uppercase}}.episode-grid{{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:1px;background:#343c38;border:1px solid #343c38}}.episode-card{{background:#0e1412;display:flex;min-width:0;flex-direction:column;transition:.2s}}.episode-card:hover{{background:#141b18}}.episode-card img{{width:100%;aspect-ratio:16/10;object-fit:cover;filter:saturate(.82) brightness(.79);transition:.25s}}.episode-card:hover img{{filter:saturate(.95) brightness(.9)}}.episode-copy{{padding:25px 25px 28px;display:flex;flex:1;flex-direction:column;min-height:290px}}.episode-copy>span{{color:#e44238;font-size:.53rem;letter-spacing:.14em;text-transform:uppercase}}.episode-copy h2{{font:400 clamp(1.8rem,2.4vw,2.75rem)/.96 "Oswald",sans-serif;text-transform:uppercase;margin:14px 0 15px}}.episode-copy p{{color:#929c95;font-size:.66rem;line-height:1.7;margin:0}}.episode-copy b{{margin-top:auto;padding-top:24px;font-size:.54rem;letter-spacing:.12em;text-transform:uppercase}}.source-note{{color:#747e77;font-size:.55rem;margin-top:22px;text-align:right}}.source-note a{{text-decoration:underline;text-underline-offset:3px}}@media(max-width:1160px){{.episode-grid{{grid-template-columns:repeat(2,1fr)}}}}@media(max-width:650px){{.episode-grid{{grid-template-columns:1fr}}.episode-copy{{min-height:240px}}.season-head{{align-items:start;flex-direction:column;gap:18px}}}}
    </style>{ASSETS}{NAV_ASSET}</head><body>{HEADER}<main><section class="hero"><div class="shell"><div class="crumb"><a href="/transcripts/">Transcripts</a> &nbsp;/&nbsp; Season {season}</div><div class="eyebrow">{years}</div><h1>Season {season}</h1><p>{intro} Read each episode without timestamps, with dialogue attributed to its speaker and divided into searchable scenes.</p><div class="summary"><div class="stat"><b>{len(episodes)}</b><span>Transcripts live</span></div><div class="stat"><b>{total}</b><span>Episodes total</span></div><div class="stat"><b>{season}X</b><span>Production files</span></div></div></div></section><section class="episodes"><div class="shell"><div class="season-head"><div><div class="eyebrow">Episode files</div><h2>Read Season {season}</h2></div><span>Broadcast order · Four across</span></div><div class="episode-grid">{''.join(cards)}</div></div></section>{navigation((f"/transcripts/season-{season-1}/",f"Season {season-1}") if season>1 else None,(f"/transcripts/season-{season+1}/",f"Season {season+1}") if season<9 else None,"Season navigation")}</main><footer><div class="shell footer-row">BOGGSFILES · TRANSCRIPT ARCHIVE <span><a href="/">Home</a> · <a href="/transcripts/">All seasons</a></span></div></footer></body></html>'''


def placeholder(season: int) -> str:
    return f'''<!doctype html><html lang="en"><head><title>Season {season} Transcripts - Boggsfiles</title>{HEAD}<style>{BASE}.pending{{padding:110px 0 160px}}.pending-box{{border:1px solid #343c38;padding:70px;background:#0e1412}}.pending h1{{font:400 clamp(4rem,9vw,9rem)/.9 "Oswald",sans-serif;text-transform:uppercase;margin:15px 0 25px}}.pending p{{color:#929c95;max-width:620px}}.pending a{{display:inline-block;margin-top:28px;color:#e44238;font-size:.6rem;text-transform:uppercase;letter-spacing:.13em}}@media(max-width:650px){{.pending-box{{padding:42px 28px}}}}</style>{ASSETS}{NAV_ASSET}</head><body>{HEADER}<main class="pending"><div class="shell"><div class="pending-box"><div class="eyebrow">Transcript collection</div><h1>Season {season}</h1><p>This season’s character-labelled DVD transcripts are being prepared for the Boggsfiles archive.</p><a href="/transcripts/">← Return to all seasons</a></div></div>{navigation((f"/transcripts/season-{season-1}/",f"Season {season-1}") if season>1 else None,(f"/transcripts/season-{season+1}/",f"Season {season+1}") if season<9 else None,"Season navigation")}</main><footer><div class="shell footer-row">BOGGSFILES · TRANSCRIPT ARCHIVE <span><a href="/">Home</a></span></div></footer></body></html>'''


def main() -> None:
    root=Path("dist/transcripts")
    (root/"index.html").write_text(season_landing(),encoding="utf-8")
    for season, episodes in SEASONS.items():
        directory=root/f"season-{season}"
        directory.mkdir(parents=True,exist_ok=True)
        (directory/"index.html").write_text(season_page(season, episodes),encoding="utf-8")
    for season in range(9,10):
        directory=root/f"season-{season}"
        directory.mkdir(parents=True,exist_ok=True)
        (directory/"index.html").write_text(placeholder(season),encoding="utf-8")


if __name__ == "__main__":
    main()
